data_path: "https://minio.lab.sspcloud.fr/mthomassin/stage3A/data/raw/csic_database.csv"
models:
  RandomForestClassifier:
    random_state: 1000
  KNeighborsClassifier:
    n_neighbors: 9
  DecisionTreeClassifier:
    random_state: 2
  LogisticRegression:
    random_state: 42
    max_iter: 1000
  SVC:
    kernel: 'rbf'
    C: 1.0
  GaussianNB:
    var_smoothing: 1e-9
  RNN:
    units: 50
    activation: relu
    optimizer: Adam
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: ['accuracy']
    epochs: 50
    batch_size: 32
  ANN:
    layers:
      - Dense:
          units: 50
          activation: relu
    optimizer: Adam
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: ['accuracy']
    epochs: 30
    batch_size: 32
  CNN:
    layers:
      - Flatten:
          input_shape: (x_tr_np.shape[1],)
      - Dense:
          units: 64
          activation: relu
      - Dense:
          units: 32
          activation: relu
      - Dense:
          units: 1
          activation: sigmoid
    optimizer: Adam
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: ['accuracy']
    epochs: 30
    batch_size: 32
  LSTM:
    units: 50
    activation: relu
    optimizer: Adam
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: ['accuracy']
    epochs: 25
    batch_size: 32
