apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-role-binding
  namespace: user-mthomassin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: user-mthomassin
roleRef:
  kind: Role
  name: argo-role
  apiGroup: rbac.authorization.k8s.io
