apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ml-soc-random-forest-training-workflow-
spec:
  serviceAccountName: workflow
  entrypoint: main
  arguments:
    parameters:
      - name: mlflow-tracking-uri
        value: user-mthomassin-mlflow.user.lab.sspcloud.fr
      - name: mlflow-experiment-name
        value: random_forest_detection
      - name: model-training-conf-list
        value: |
          [
            { "n_estimators": 50, "max_leaf_nodes": 5 },
            { "n_estimators": 50, "max_leaf_nodes": 10 },
            { "n_estimators": 50, "max_leaf_nodes": 50 },
            { "n_estimators": 100, "max_leaf_nodes": 5 },
            { "n_estimators": 100, "max_leaf_nodes": 10 },
            { "n_estimators": 100, "max_leaf_nodes": 50 },
            { "n_estimators": 200, "max_leaf_nodes": 5 },
            { "n_estimators": 200, "max_leaf_nodes": 10 },
            { "n_estimators": 200, "max_leaf_nodes": 50 }
          ]
  parallelism: 10  # Add this line to increase the number of parallel pods
  templates:
    - name: main
      dag:
        tasks:
          - name: start-pipeline
            template: start-pipeline-wt
          - name: train-model-with-params
            dependencies: [start-pipeline]
            template: run-model-training-wt
            arguments:
              parameters:
                - name: n_estimators
                  value: "{{item.n_estimators}}"
                - name: max_leaf_nodes
                  value: "{{item.max_leaf_nodes}}"
            withParam: "{{workflow.parameters.model-training-conf-list}}"

    - name: start-pipeline-wt
      container:
        image: busybox
        command: [sh, -c]
        args: ["echo Starting pipeline"]

    - name: run-model-training-wt
      inputs:
        parameters:
          - name: n_estimators
          - name: max_leaf_nodes
      container:
        image: wolfpackstatmathieu/ml-soc:1.0.0
        imagePullPolicy: Always
        command: [sh, -c]
        args: ["python main.py --n_estimators {{inputs.parameters.n_estimators}} --max_leaf_nodes {{inputs.parameters.max_leaf_nodes}}"]
        env:
          - name: MLFLOW_TRACKING_URI
            value: "{{workflow.parameters.mlflow-tracking-uri}}"
          - name: MLFLOW_EXPERIMENT_NAME
            value: "{{workflow.parameters.mlflow-experiment-name}}"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: aws_secret_access_key
          - name: AWS_DEFAULT_REGION
            value: "us-east-1"
          - name: AWS_SESSION_TOKEN
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: aws_session_token
