apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ml-soc-random-forest-training-workflow-
spec:
  serviceAccountName: workflow
  entrypoint: main
  arguments:
    parameters:
      - name: mlflow-tracking-uri
        value: https://user-mthomassin-mlflow.user.lab.sspcloud.fr
      - name: mlflow-experiment-name
        value: random_forest_detection
      - name: model-training-conf-list
        value: |
          [
            { "n_estimators": 50, "max_leaf_nodes": 5 },
            { "n_estimators": 50, "max_leaf_nodes": 10 },
            { "n_estimators": 50, "max_leaf_nodes": 50 },
            { "n_estimators": 100, "max_leaf_nodes": 5 },
            { "n_estimators": 100, "max_leaf_nodes": 10 },
            { "n_estimators": 100, "max_leaf_nodes": 50 },
            { "n_estimators": 200, "max_leaf_nodes": 5 },
            { "n_estimators": 200, "max_leaf_nodes": 10 },
            { "n_estimators": 200, "max_leaf_nodes": 50 }
          ]
  templates:
    - name: main
      dag:
        tasks:
          - name: start-pipeline
            template: start-pipeline-wt
          - name: train-model-with-params
            dependencies: [start-pipeline]
            template: run-model-training-wt
            arguments:
              parameters:
                - name: n_estimators
                  value: "{{item.n_estimators}}"
                - name: max_leaf_nodes
                  value: "{{item.max_leaf_nodes}}"
            withParam: "{{workflow.parameters.model-training-conf-list}}"

    - name: start-pipeline-wt
      container:
        image: busybox
        command: [sh, -c]
        args: ["echo Starting pipeline"]

    - name: run-model-training-wt
      inputs:
        parameters:
          - name: n_estimators
          - name: max_leaf_nodes
      container:
        image: wolfpackstatmathieu/ml-soc:1.0.0
        imagePullPolicy: Always
        command: [sh, -c]
        args: ["python main.py --n_estimators {{inputs.parameters.n_estimators}} --max_leaf_nodes {{inputs.parameters.max_leaf_nodes}}"]
        env:
          - name: MLFLOW_TRACKING_URI
            value: "{{workflow.parameters.mlflow-tracking-uri}}"
          - name: MLFLOW_EXPERIMENT_NAME
            value: "{{workflow.parameters.mlflow-experiment-name}}"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: aws_access_key_id
                value: "RN3WUMV3YLOB4B1VZ8UP"
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: aws_secret_access_key
                value: "7XjPe9+spKKDGmHExGIkK28rYd7Ipob6c1A7ekfd"
          - name: AWS_SESSION_TOKEN
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: aws_session_token
                value: "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJSTjNXVU1WM1lMT0I0QjFWWjhVUCIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sImF1ZCI6WyJtaW5pby1kYXRhbm9kZSIsIm9ueXhpYSIsImFjY291bnQiXSwiYXV0aF90aW1lIjoxNzIxNjM0OTQ1LCJhenAiOiJvbnl4aWEiLCJlbWFpbCI6Im1hdGhpZXUudGhvbWFzc2luQGVsZXZlLmVuc2FpLmZyIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImV4cCI6MTcyMjI2NzIwOCwiZmFtaWx5X25hbWUiOiJUaG9tYXNzaW4iLCJnaXZlbl9uYW1lIjoiTWF0aGlldSIsImdyb3VwcyI6WyJVU0VSX09OWVhJQSJdLCJpYXQiOjE3MjE2NjI0MDgsImlzcyI6Imh0dHBzOi8vYXV0aC5sYWIuc3NwY2xvdWQuZnIvYXV0aC9yZWFsbXMvc3NwY2xvdWQiLCJqdGkiOiI2Y2ZjOWUxYi0zYjUzLTRhMWQtYTNhZS1lYTRmZTExY2NjOTgiLCJuYW1lIjoiTWF0aGlldSBUaG9tYXNzaW4iLCJwb2xpY3kiOiJzdHNvbmx5IiwicHJlZmVycmVkX3VzZXJuYW1lIjoibXRob21hc3NpbiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIiwiZGVmYXVsdC1yb2xlcy1zc3BjbG91ZCJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZ3JvdXBzIGVtYWlsIiwic2Vzc2lvbl9zdGF0ZSI6IjIwY2IwYTJmLWU2ZmMtNGZlNS04NTZhLTczZmVjZDFkNTVkNyIsInNpZCI6IjIwY2IwYTJmLWU2ZmMtNGZlNS04NTZhLTczZmVjZDFkNTVkNyIsInN1YiI6IjM5ZGIzOTc1LWMyMGQtNGFhZC1hNGY3LTRkNDkyNzRlNThmNiIsInR5cCI6IkJlYXJlciJ9.gXgzWEBxMAlgV0uoRWuqWMz0NWNht0TQFXLWh2rTXk0aN5UAs1Bq3VNtD6pGabSYEuVPkPPYggIIYz3euuLr1Q"
          - name: AWS_DEFAULT_REGION
            value: "us-east-1"
          - name: AWS_S3_ENDPOINT
            value: "minio.lab.sspcloud.fr"
          - name: MC_HOST_myminio
            value: "https://minio.lab.sspcloud.fr"


